// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetConfig():Promise<config.Config>;

export function SetProviderSettings(arg1:string,arg2:config.Provider):Promise<void>;

export function SetSettings(arg1:Record<string, any>):Promise<void>;
