// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetInfo() {
  return window['go']['main']['App']['GetInfo']();
}

export function SetProviderSettings(arg1, arg2) {
  return window['go']['main']['App']['SetProviderSettings'](arg1, arg2);
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}
